# Generated by Django 4.1 on 2024-08-24 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
        ('part', '0001_initial'),
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='parts',
            field=models.ManyToManyField(blank=True, to='part.parts'),
        ),
        migrations.AddField(
            model_name='formula',
            name='product_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.productformat'),
        ),
        migrations.AddField(
            model_name='formula',
            name='product_quality',
            field=models.ManyToManyField(blank=True, to='utilities.productqualities'),
        ),
        migrations.AddField(
            model_name='formula',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.producttype'),
        ),
        migrations.AddField(
            model_name='formula',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.subcategory'),
        ),
        migrations.AddField(
            model_name='folderformula',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
