# Generated by Django 4.1 on 2024-08-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='activeFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parts',
            name='lastChangedUser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
