# Generated by Django 4.1 on 2024-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_parts_activeflag_parts_lastchangeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdocument',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
