# Generated by Django 4.1 on 2024-09-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_partdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdocument',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partdocument',
            name='status',
            field=models.CharField(default='In Progress', max_length=255),
        ),
    ]
