# Generated by Django 4.1 on 2024-09-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0006_alter_vendorparts_status'),
        ('part', '0005_partdocument_notes_alter_partdocument_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partdocument',
            name='vendorparts',
        ),
        migrations.AddField(
            model_name='partdocument',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='part.parts'),
        ),
        migrations.AddField(
            model_name='partdocument',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
